name: pagla_chat
description: "A new Flutter project for Pagla Chat."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # --- ভয়েস চ্যাট (Agora) ---
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.0
  
  # --- ফায়ারবেস (Firebase) ---
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8        # নতুন: গুগল লগইন এর জন্য
  cloud_firestore: ^4.15.8      # নতুন: ডাটা সেভ করার জন্য
  firebase_database: ^10.4.9
  firebase_remote_config: ^4.3.8
  
  # --- গুগল লগইন ---
  google_sign_in: ^6.2.1        # নতুন: রিয়েল গুগল লগইন
  
  # --- ইউটিউব সচল করার জন্য ---
  youtube_player_flutter: ^8.1.2 # নতুন: রিয়েল ভিডিও বোর্ড
  
  # --- অন্যান্য দরকারি প্যাকেজ ---
  package_info_plus: ^5.0.1
  cached_network_image: ^3.3.0
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#0F0F1E"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
