name: pagla_app
description: "Achat Style Voice Chat App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.jpg"
  adaptive_icon_background: "#1A1A2E"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.jpg
